### PR TITLE
:recycle: refactor PageWithSkillList.tsx

### PR DESCRIPTION
**Pull request by benjaminbrgs**
Closes https://github.com/Zenika/skillZ/issues/186

At the same time, I've refactored the page because they was duplicate code and useless network calls

### CODE REVIEW

**Review by MailyLehoux — CHANGES_REQUESTED** [review]
Nice PR, it updates the graph nicely ! 

And the refacto is ok for me.

src/graphql/queries/categorie.ts -> Should be good to avoid french the most as possible 

It didn't update the list when I've added a skill. In this case I've added ActiveMQ, but I had to refresh the page to see it disappear from the list

Capture d’écran de 2022-09-13 16-19-26

**Comment by benjaminbrgs** [comment]
Good catch! Should be working now

**Comment by MailyLehoux** [comment]
I've re requested but I just would approved this PR ooppps. It's ok for me ! It works good :100:

**Review by MailyLehoux — APPROVED** [review]
:+1:

**Pull request merged**
