### PR TITLE
:lipstick: improve graph ux design

### PR DESCRIPTION
**Pull request by ThomG317**

### CODE REVIEW

**Review by benjaminbrgs — COMMENTED** [review]
I think there is a problem here 😅
image

**Comment by ThomG317** [comment]
> I think there is a problem here 😅 image

It should be ok now.

**Review by benjaminbrgs — APPROVED** [review]
Seems good to me, gg 👍🏻

**Comment by benjaminbrgs** [comment]
I close this PR as https://github.com/Zenika/skillZ/pull/380 brings a new version of skill graph

**Pull request closed without merging**
