### PR TITLE
 :lipstick: add hover state for all CTA elements

### PR DESCRIPTION
**Pull request by ThomG317**

### CODE REVIEW

**Review by benjaminbrgs — CHANGES_REQUESTED** [review]
Looks nice 👍🏼
Two problems I've seen so far

1. On the top bar, the space between the title and the icon in a menu item is too big and the the admin notification touch the border of the window
image

2. When clicking on a title of a skill, a description modal of this skills is opening but it's impossible to close it.
image

**Comment by ThomG317** [comment]
@benjaminbrgs I'll try to see If I have some time to fix 1.

2. I think to was already there before, to be confirmed though.

**Comment by MailyLehoux** [comment]
Nice PR :+1: gg !

The bug with the modal isn't exists in main branch, we should fix this before merging

Also, the hover isn't exists in the profils panels. We should add this on it as well 
Capture d’écran de 2022-11-28 11-04-44

**Comment by benjaminbrgs** [comment]
@ThomG317 @MailyLehoux All threads should be resolved now :))

**Review by benjaminbrgs — APPROVED** [review]

**Review by MailyLehoux — APPROVED** [review]

**Pull request merged**
