### PR TITLE
[WIP] Feat/filters on search

### LINKED ISSUE #152: Possibility to add filters for a search
Capture d’écran de 2022-04-13 10-33-13

https://www.figma.com/proto/0kOnLSj4J9FPcAvlRyupGI/skillZ?node-id=48%3A116&scaling=scale-down&page-id=0%3A1&starting-point-node-id=107%3A0

### PR DESCRIPTION
**Pull request by MailyLehoux**
resolve #152

### CODE REVIEW

**Comment by Ked57** [comment]
For icons I recommend you use https://react-icons.github.io/react-icons instead of PNGs

May I ask why use REST endpoints for this ?

**Comment by MailyLehoux** [comment]
Oh thanks for the link ! It seems good 

Yes it was for tests, I forgot that I worked on it on this branch. It will be removed on the next push

**Comment by MailyLehoux** [comment]
Capture d’écran de 2022-06-15 17-01-39
Capture d’écran de 2022-06-15 17-02-55

Refered to the Figma, I did this box to filter content. We could imagine to add a field to filter by agency as well if it's good for you. 

If you have any suggestions/comments about the ui/ux please tell me

**Comment by jeanphibaconnais** [comment]
by agency it's a good idea !

**Pull request closed without merging**
