### PR TITLE
✅ E2E Tests on profile page

### PR DESCRIPTION
**Pull request by benjaminbrgs**
Closes https://github.com/Zenika/skillZ/issues/219

### CODE REVIEW

**Comment by MailyLehoux** [comment]
Its working with Electron v102 

Capture d’écran de 2022-09-28 14-23-08

Seems good, all tests passed it's ok for me :+1:

**Review by MailyLehoux — APPROVED** [review]

**Comment by Ked57** [comment]
Hello, I have a suggestion, you might want to try https://testing-library.com/docs/cypress-testing-library/intro/ for selectors so you don't have to set ids and have weird selectors in cypress 😄

**Comment by benjaminbrgs** [comment]
Thanks for the suggestion @Ked57 !
I don't like using the text of element to select it. First if the text changes, you also have to change all e2e tests using it. Second it can be more difficult if we want to test with different languages.

However, I've installed this library to simplify the selectors with `data-testid` instead of `id` attributes

**Comment by Ked57** [comment]
Using test, labels and roles to select elements allow you to write tests to be as close as possible to the way users use your application, that's the goal of testing-library (you can read details here https://testing-library.com/docs/dom-testing-library/intro ) and the guiding principles ( https://testing-library.com/docs/guiding-principles/ ).

So yes, if text changes you have to update your tests because the way users use the app changed, makes sense to me 😄 It goes the other way around, and that's where this method is interesting. If the user experience changed and this was not intended, your tests might still pass using data-testid and common selectors whereas selecting by text, label or role is much more likely to alert of that change.

In the end it's an industry wide, generally accepted good practice to do it this way: [The more your tests resemble the way your software is used, the more confidence they can give you.](https://twitter.com/kentcdodds/status/977018512689455106)

**Comment by benjaminbrgs** [comment]
It makes sense even if I still believe it can be more difficult for specific situation like button without text (icon only).
 
I've tried to implement it for all profile page tests in the last commit 😃

**Review by Ked57 — APPROVED** [review]
I think using `parent()` after a findBy is fine, sometime there's just no other choice ! Also I didn't really think about testability when I wrote this app (that's why you should write tests as you go ...) so some components are really hard to tests so it's fine.

You could replace `cy.contains("...");` with `cy.findBy("...").should("exist")` for clarity but honestly I'm probably nitpicking at this point

**Pull request merged**
